name: Node.js Package

on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'master'
      - name: Setup PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
          registry-url: https://npm.pkg.github.com/
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm run build-lib
      - name: Publish
        working-directory: ./dist/ng-pattern-mask
        run: pnpm pack --no-git-checks
      - name: Run Publish
        working-directory: ./dist/ng-pattern-mask
        run: pnpm publish --no-git-checks
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}