name: Build and publish library to npm.js registry

on:
  release:
    types: [created]

jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'master'
      - name: Setup NPM
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Install dependencies
        run: npm i
      - name: Build
        run: npm run build-lib
      - name: Pack
        working-directory: ./dist/ng-pattern-mask
        run: npm pack
      - name: Set package registry
        run: npm config set registry https://registry.npmjs.org
      # - name: Npm registry authentication
      #   run: npm set //registry.npmjs.org/:_authToken ${{secrets.NPM_TOKEN}}
      # - name: Create npmrc
      #   working-directory: ./dist/ng-pattern-mask
      #   run: echo //registry.npmjs.org/:_authToken=${{secrets.NPM_TOKEN}} > /home/runner/work/ng-pattern-mask/ng-pattern-mask/dist/ng-pattern-mask/.npmrc
      - name: NPM whoami
        run: npm whoami
      - name: Publish
        working-directory: ./dist/ng-pattern-mask
        run: npm publish --access public 
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          token: ${{secrets.NPM_TOKEN}}