name: Build and publish library

on:
  release:
    types: [created]

jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'master'
      - name: Setup NPM
        uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - name: Install dependencies
        run: npm i
      - name: Build
        run: npm run build-lib
      - name: Pack
        working-directory: ./dist/ng-pattern-mask
        run: npm pack
      - name: Publish
        working-directory: ./dist/ng-pattern-mask
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}