name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'master'
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
      - run: pnpm install
      - run: pnpm run build-lib

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
        with:
          ref: 'master'
      - uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
          registry-url: https://npm.pkg.github.com/
      - run: pnpm install
      - run: pnpm run build-lib
      - name: Run Publish
        working-directory: ./dist/ng-pattern-mask
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}