name: Build and publish library to npm.js registry

on:
  release:
    types: [created]

jobs:
  build-publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: 'master'
      - name: Setup NPM
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm i
      - name: Build
        run: npm run build-lib
      - name: Pack
        working-directory: ./dist/ng-pattern-mask
        run: npm pack
      - name: Set package registry
        run: npm config set registry https://registry.npmjs.org
      - name: Npm registry authentication
        run: npm set //registry.npmjs.org/:_authToken ${{ secrets.NPM_TOKEN }}
      - name: Publish
        working-directory: ./dist/ng-pattern-mask
        run: npm publish --access public --ignore-scripts --registry='https://registry.npmjs.org'
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}